model_list:
  - model_name: saia/mistral-large-3-675b
    litellm_params:
      model: openai/mistral-large-3-675b-instruct-2512
      api_key: os.environ/SAIA_API_KEY
      api_base: https://chat-ai.academiccloud.de/v1

  - model_name: saia/glm-4.7
    litellm_params:
      model: openai/glm-4.7
      api_key: os.environ/SAIA_API_KEY
      api_base: https://chat-ai.academiccloud.de/v1

  - model_name: saia/qwen3-235b-a22b
    litellm_params:
      model: openai/qwen3-235b-a22b
      api_key: os.environ/SAIA_API_KEY
      api_base: https://chat-ai.academiccloud.de/v1

  - model_name: saia/qwen3.5-397b-a17b
    litellm_params:
      model: openai/Qwen3.5-397B-A17B-GPTQ-Int4
      api_key: os.environ/SAIA_API_KEY
      api_base: https://chat-ai.academiccloud.de/v1

  - model_name: saia/qwen3.5-122b-a10b
    litellm_params:
      model: openai/Qwen3.5-122B-A10B-GPTQ-Int4
      api_key: os.environ/SAIA_API_KEY
      api_base: https://chat-ai.academiccloud.de/v1

  - model_name: saia/devstral-2-123b-instruct-2512
    litellm_params:
      model: openai/Devstral-2-123B-Instruct-2512
      api_key: os.environ/SAIA_API_KEY
      api_base: https://chat-ai.academiccloud.de/v1

  - model_name: saia/internvl-3.5-30b-a3b
    litellm_params:
      model: openai/InternVL3_5-30B-A3B-HF
      api_key: os.environ/SAIA_API_KEY
      api_base: https://chat-ai.academiccloud.de/v1

  - model_name: qwen3.5-9b-81
    litellm_params:
      model: openai/qwen3.5-9b-q4_k_m.gguf
      api_key: none
      api_base: http://192.168.0.81:8080/v1

  - model_name: qwen3.6-35b
    litellm_params:
      model: openai/qwen3.6-35b
      api_key: none
      api_base: http://192.168.0.27:8000/v1

  - model_name: qwen3.6-35b
    litellm_params:
      model: openai/qwen3.6-35b
      api_key: none
      api_base: http://192.168.0.176:8000/v1

  - model_name: gemma-4
    litellm_params:
      model: openai/google_gemma-4-26B-A4B-it-Q4_K_M.gguf
      api_key: not-needed
      api_base: http://host.docker.internal:8080/v1

router_settings:
  fallbacks:
    - { "saia/mistral-large-3-675b": ["saia/glm-4.7"] }
  num_retries: 3
  allowed_fails: 3
  cooldown_time: 30
